### ISSUE TITLE
incorrect header check

### ISSUE THREAD

**Issue by snpbutz** [spacem/dngearsim-desktop#2]
Hi.
i was trying on a private server of my region, but i'm getting an error while extracting data from the client,

![image](https://user-images.githubusercontent.com/40307284/41502766-28991968-7198-11e8-9f34-96014b76959e.png)

**Comment by spacem** [comment]
I am not that familiar with pak file format but I think this error comes from zlib (Eye uses deflate compression in their files). Maybe that private server uses a different file format. It could also be your files are corrupted? I heard some mod makers would deliberately use a different pak file format so they could not be easily extracted by community tools. Maybe your server owners do the same?

Sorry but I personally will not be implementing support for private servers any time soon. If someone submitted a pull request that resolved the issue I would consider merging and updating the desktop dngearsim however I would not be surprised if there were other issues.

**Comment by snpbutz** [comment]
yes the server use a different file format (.RFS), and also uses VM protect
